language: cpp
sudo: required
dist: trusty

env:
  global:
    - secure: "cIkSIuSmwqo8uZVl+Dhpq2lFbyOKg5pkIazFyRLlyqUVALVyzPnrBXtpsS2Y0B4V2niHTUrKY5gLuSlCuQ+6JtPThttKA+YQFF2gdQbTuoIEyzNXjLSRvwEkp33XK4n+VkG1y7QT6PCKoGjvWWnFYKxghV4wp9/UWBWH7Qgxhc+y5rV3388KHqGw0hlg1ylIbbEYsUsPDb62QBR2VJmOKx+mizioYGuClyQXTeqTiFAZnrgH/4lTXETEfjekr6TndAXwk1qwq+dlsZL1lPMmgJlnjsSGKW3MPjQdwQXi6+qTQIzj1iOcgqID6aux74WTkqwsDV+hEko8QJAPJaJnYu8MCM9+2GnhfLpSwU+vAmUxwcc9zrie3TPJnx9xe3qnKhFYPA7OtwM5/MGYojvLnzdV3/m9+9rjex+0XZwX0zH3fnnGYzc0wcqBJaQjaMc2OBtp5Fs8hj+a2xBWO86SUFFuWCdD7TvrQ8Ctwl2kO4s05OgIHxMneDhicLg6AR8pcdITRggbs4ufvBmT+oc5ul/vxgXJI+DiUm3U8vObNZi9xLj6uIJpiuHZ/SN0FR4u4MW9UjlrwPivFYcUBaxKdIEwBrcEkaHfjyYlLhJ9Q2wO2bp5bMD4RSLG5Lzgfb1OoZhmLqRSOFpGyfZXPm8c0PnUtCqY8KfTXnvQFDiTFw0="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "eprikazchikov/thunder"
      description: "Cross Platform Game Engine"
    notification_email: eprikazchikov@mail.ru
    build_command_prepend: "qbs --version"
    build_command: "qbs build"
    branch_pattern: coverity_scan

matrix:
  include:
    - os: osx
      before_install:
        - brew update
        - brew install qbs
      script:
        - qbs --version
        - qbs setup-toolchains --detect
        - qbs setup-qt /usr/local/opt/qt/bin/qmake qt-brew
        - qbs config profiles.qt-brew.baseProfile xcode-macosx-x86_64
        - qbs config defaultProfile qt-brew
        - qbs install --install-root install --all-products config:release
        - /usr/local/opt/qt/bin/macdeployqt install/sdk/2.0/macos/x86_64/bin/WorldEditor.app
        - tar -czvf ThunderEngine-macos-x86_64.tar.gz install/sdk
      after_success:
        "curl --ftp-create-dirs -T ThunderEngine-macos-x86_64.tar.gz -u $FTP_USER:$FTP_PASSWORD ftp://ftp.thunderengine.ru/ThunderEngine-macos-x86_64.tar.gz"
