clone_depth: 200
version: '1.0.{build}'

environment:
  matrix:
    - QTDIR: C:\Qt\5.9.3\msvc2015

configuration: Release

install:
  - choco install -y qbs --version 1.10.0
  - nuget install secure-file -ExcludeVersion
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - qbs --version
  - qbs setup-toolchains --detect
  - qbs setup-qt %QTDIR%\bin\qmake.exe qt
  - qbs config defaultProfile qt
  - qbs build --all-products release

cache:
  - C:\Users\appveyor\.m2
